name: CI

on:
  push:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson

      - name: Build MAKE_SMAP_L2C_V50_ascii
        run: |
          meson setup build .
          meson compile -C build

      - name: Archive MAKE_SMAP_L2C_V50_ascii
        uses: actions/upload-artifact@v3
        with:
          name: MAKE_SMAP_L2C_V50_ascii
          path: build/MAKE_SMAP_L2C_V50_ascii
